version: 0.2
phases:
  build:
    commands:
      - cd dash
      - sam build --parameter-overrides 'SecurityGroupId=$SECURITY_GROUP_ID Subnet1Id=$SUBNET_1_ID Subnet2Id=$SUBNET_Y_ID DBHost=$DB_HOST DBPort=$DB_PORT DBUser=$DB_USER DBPassword=$DB_PASSWORD DBName=$DB_NAME'
      - sam deploy --stack_name elasticcode-dashboard --no-confirm-changeset --no-fail-on-empty-changeset 