AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 600
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: Dashboard
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_NAME: !Ref DBName
        SECURITY_GROUP_ID: !Ref SecurityGroupId
        SUBNET_1_ID: !Ref Subnet1Id
        SUBNET_2_ID: !Ref Subnet2Id
        USER_POOL_ID: !Ref UserPoolId
        ACESS_KEY_ID: !Ref AcessKeyId
        SECRET_ACESS_KEY: !Ref SecretAcessKey
        REPO_OWNER: !Ref RepoOwner
        REPO_NAME: !Ref RepoName
        GITHUB_TOKEN: !Ref GitHubToken

Parameters:
  SecurityGroupId:
    Description: Security Group for the application
    Type: String
  Subnet1Id:
    Description: Subnet Id for the first subnet
    Type: String
  Subnet2Id:
    Description: Subnet Id for the second subnet
    Type: String
  DBHost:
    Type: String
  DBPort:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
  DBName:
    Type: String
  UserPoolId:
    Type: String
  AcessKeyId:
    Type: String
  SecretAcessKey:
    Type: String
  RepoOwner:
    Type: String
  RepoName:
    Type: String
  GitHubToken:
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowOrigin: "'*'"
  
  DashboardApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.br.agilize.dash.handler.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Policies:
        - AWSLambda_FullAccess
        - AmazonEC2FullAccess
        - AmazonAPIGatewayAdministrator
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
