AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: Dashboard
        SECRET_NAME: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_USER: !Ref DBUser
        DB_PASSWORD: !Ref DBPassword
        DB_NAME: !Ref DBName
        SECURITY_GROUP_ID: !Ref SecurityGroupId
        SUBNET_1_ID: !Ref Subnet1Id
        SUBNET_2_ID: !Ref Subnet2Id

Parameters:
  SecurityGroupId:
    Description: Security Group for the application
    Type: String
  Subnet1Id:
    Description: Subnet Id for the first subnet
    Type: String
  Subnet2Id:
    Description: Subnet Id for the second subnet
    Type: String
  DatabaseSecretName:
    Description: The name of the secret holding database credentials
    Type: String
  DBHost:
    Type: String
  DBPort:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
  DBName:
    Type: String

Resources:
  DashboardApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.br.agilize.dash.handler.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}
        - AWSLambda_FullAccess
        - AmazonEC2FullAccess
        - SecretsManagerReadWrite
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowOrigin: "'*'"